### ISSUE TITLE
$info returning Github rate limit warning

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/ProcessWireUpgrade#26]
https://github.com/ryancramerdesign/ProcessWireUpgrade/blob/309b448048a07a98dc6b56cd7130ed6219b162f3/ProcessWireUpgradeCheck.module#L336 results in this error:
```
PHP Warning: Illegal string offset 'name'
```
but the problem is that $info is returning:
```
https://developer.github.com/v3/#rate-limiting
API rate limit exceeded for xx.xx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit.
```

**Comment by cb2004** [comment]
@adrianbj @ryancramerdesign with the latest version of the module (0.0.9) line 381, my workaround is:

`if(isset($info['name'])) $name = $info['name'];`

**Comment by matjazpotocnik** [comment]
@cb2004 @adrianbj Looks like this is fixed in https://github.com/ryancramerdesign/ProcessWireUpgrade/commit/9e5c63aa33ce5cc01bdb1cf758e501871409dff0 ?

**Comment by adrianbj** [comment]
@matjazpotocnik - are you talking about this line: https://github.com/ryancramerdesign/ProcessWireUpgrade/commit/9e5c63aa33ce5cc01bdb1cf758e501871409dff0#diff-3fc5e28f5bae5116fcf7268c5fa7a21fa10c4896848e138f969243035028facbR382

Honestly I haven't seen this warning in years anyway - not sure if Github upped their rate limit and that is why I haven't seen it. Regardless it does seem like that change should prevent it showing again, so I'll close this - thanks for reminding me about it.
