### ISSUE TITLE
PHP Warning: Undefined array key "local" 

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/ProcessWireUpgrade#32]
There are warnings after performing upgrade check via Setup -> Upgrades, please see screenshot.

PHP Warning: Undefined array key "local" in ...\ProcessWireUpgradeCheck.module:282
PHP Warning: Undefined array key "title" in ...\ProcessWireUpgrade.module:276
PHP Warning: Undefined array key "local" in ...\ProcessWireUpgrade.module:301

What's also odd is the list of two modules that I have recently uninstalled and deleted, Dashboard and FieldtypeStreetAddress, so I don't expect to see them on the list. I looked into ProcessWireUpgradeCheck.module around line 282 and for FieldtypeStreetAddress module `$versions[$name]` contains only `'remote' => '1.1.2'`. Maybe it has nothing to do with this module  but rather with invalid data regarding installed modules? After hitting refresh button the error went away. Cache issue?

![image](https://user-images.githubusercontent.com/7663992/115603800-e1d2e180-a2e0-11eb-95b4-834db4929181.png)

**Comment by matjazpotocnik** [comment]
Edit: the error come back after I deleted more modules. Again, hitting refresh button solved the issue.

**Comment by matjazpotocnik** [comment]
Fixed in https://github.com/ryancramerdesign/ProcessWireUpgrade/commit/9e5c63aa33ce5cc01bdb1cf758e501871409dff0. Thank you.

**Comment by ryancramerdesign** [comment]
Thanks, I learned this from your issue report but it got bundled in with
other updates.
